version: "3.7"

services:
  nginx:
    image: nginx:1.19.5
    networks:
      - taroun_1ban_network
    volumes:
      - taroun_1ban_static:/data/static/
      - taroun_1ban_media:/data/media/
      - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  django:
    image: taroun_1ban_django:4
    networks:
      - taroun_1ban_network
    volumes:
      - taroun_1ban_static:/home/gis_1ban_1/staticfiles/
      - taroun_1ban_media:/home/gis_1ban_1/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - taroun_1ban_network
    volumes:
      - taroun_mariadb:/var/lib/mysql
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: tata1212
      MARIADB_ROOT_PASSWORD: tata1212

networks:
  taroun_1ban_network:

volumes:
  taroun_1ban_static:
  taroun_1ban_media:
  taroun_mariadb:
